### ISSUE TITLE
리더께서는 업무 분담해주시기 바랍니다.

### ISSUE THREAD

**Issue by fasthill-sibling** [fasthill/Git-lecture#17]
저는 def cal(): 을 담당할 수 있습니다.

**Comment by fasthill** [comment]
다른 일정으로 바빠서 못했습니다. 곧 하도록 하겠습니다.

**Comment by paichaisw** [comment]
여기도 아무나 들어와서 보고 쓸 수 있나요?

**Comment by avacado21** [comment]
저도 업무분담해서 2명씩 짝지어서 진행하는것이 좋다고 생각합니다.
2명씩 짝짓되  2개의 프로젝트를 진행. 각각 역할을 바꾸어서.

**Comment by avacado21** [comment]
하나의 프로젝트를 2명이 2개로 진행.  팀원1/2가 프로젝트A를 진행할때  A-1/A-2로 진행. A-1에서는 팀원 1이 팀장, A-2에서는 팀원2가 팀장.

**Comment by fasthill** [comment]
closed
